spring.application.name=Candidat4TWIN2Ms
spring.cloud.config.import-check.enabled=false
spring.cloud.config.fail-fast=false
server.port=8087
# H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2
# Datasource
spring.datasource.username=Oumeima
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./Database/Data/Candidat;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# eureka config
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
